# Generated by Django 5.1.3 on 2024-11-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_author",
            field=models.BooleanField(default=False, verbose_name="Является автором?"),
        ),
    ]
