# Generated by Django 5.1.3 on 2024-11-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="descriptions",
            new_name="description",
        ),
    ]
