# Generated by Django 5.1.3 on 2024-11-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_subscription_type_of_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания подписки"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата старта подписки"
            ),
        ),
    ]
